### ISSUE TITLE
Will you be able to add the mock role manager

### ISSUE THREAD

**Issue by BeanieMen** [ShoGinn/discordjs-mock#13]

**Comment by ShoGinn** [comment]
Do you have any more specifics on what you want the role manager to do that you currently cannot do ?

**Comment by BeanieMen** [comment]
i figured out the issue, the mock client still tried to make requests using discordjs's rest api

**Comment by BeanieMen** [comment]
```
Error: Expected token to be set for this request, but none was present
 ❯ _REST.resolveRequest node_modules/@discordjs/rest/src/lib/REST.ts:314:11
 ❯ _REST.queueRequest node_modules/@discordjs/rest/src/lib/REST.ts:256:44
 ❯ _REST.request node_modules/@discordjs/rest/src/lib/REST.ts:211:31
 ❯ _REST.get node_modules/@discordjs/rest/src/lib/REST.ts:162:15
 ❯ GuildManager.fetch node_modules/discord.js/src/managers/GuildManager.js:280:41
 ❯ tests/client.ts:94:33
     92| export const client = mock.getClient(true);
     93| await client.login(process.env.TOKEN)
     94| console.log(await client.guilds.fetch())
       |                                 ^
       ```

**Comment by ShoGinn** [comment]
> ```
> Error: Expected token to be set for this request, but none was present
>  ❯ _REST.resolveRequest node_modules/@discordjs/rest/src/lib/REST.ts:314:11
>  ❯ _REST.queueRequest node_modules/@discordjs/rest/src/lib/REST.ts:256:44
>  ❯ _REST.request node_modules/@discordjs/rest/src/lib/REST.ts:211:31
>  ❯ _REST.get node_modules/@discordjs/rest/src/lib/REST.ts:162:15
>  ❯ GuildManager.fetch node_modules/discord.js/src/managers/GuildManager.js:280:41
>  ❯ tests/client.ts:94:33
>      92| export const client = mock.getClient(true);
>      93| await client.login(process.env.TOKEN)
>      94| console.log(await client.guilds.fetch())
>        |                                 ^
>        ```
> ```

I apologize that there isn't much documentation, this was my fork of another repo that didn't meet my needs.


the client.login will always try and reach out to the API unless you use an example of my mock class.

I direct inject everything so that's why i used the example in the README.md

**Comment by BeanieMen** [comment]
This wasn't a problem with client.login rather the fetch function, it tried to reach out to the api, any way to mock the api?

**Comment by BeanieMen** [comment]
Ill try to mock the api today, as client and the rest api are now separated, I believe it should be fairly simple

**Comment by ShoGinn** [comment]
There might be a slight misunderstanding. This mock is manual in nature and you would have to mock each function individually. The fetch functions are builtins that you could return mockGuild etc. 

It's a real hack to be honest cause the mock is mocking the discordJs not discord api itself.

**Comment by BeanieMen** [comment]
> There might be a slight misunderstanding. This mock is manual in nature and you would have to mock each function individually. The fetch functions are builtins that you could return mockGuild etc. 
> 
> It's a real hack to be honest cause the mock is mocking the discordJs not discord api itself. 

Yeah, after a bit of snooping around i understood that
That's why I am suggesting a mock discord rest api.
The client on its creation can take a rest api class

**Comment by BeanieMen** [comment]
So I'll try to create a custom/mock discord rest api in a week or so, slowly mocking the end points
